name: WispMobsDropOP
version: 1.0-SNAPSHOT
main: dev.yhdiamond.wispmobsdropop.WispMobsDropOP
api-version: 1.16
commands:
  wispmobsdropop:
    usage: /wispmobsdropop <start/stop>
    description: Starts the Wisp Mobs Drop OP Items challenge